### ISSUE TITLE
Generate setters with `set_` by default

### ISSUE THREAD

**Issue by cottinisimone** [Lymia/derive_setters#4]
Hello, 

First of all thank you for your library, i found it useful. The only issue i see in this is that methods are not generated by default with `set_` prefix. This should be the convention for setters methods being that is largely used in the standard library. Some examples:
- [Vec::len 140](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.len) / [Vec::set_len 107](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.set_len)
- [env::current_dir 39](https://doc.rust-lang.org/std/env/fn.current_dir.html) / [env::set_current_dir 31](https://doc.rust-lang.org/std/env/fn.set_current_dir.html)
- [env::var 27](https://doc.rust-lang.org/std/env/fn.var.html) / [env::set_var 23](https://doc.rust-lang.org/std/env/fn.set_var.html)

Moreover this change allow the use of this library and [derive_getters](https://crates.io/crates/derive-getters) in the same project being that actually this result in function names clash.

Thank you in advance

**Comment by Lymia** [comment]
I disagree with making it the default. I originally wrote this crate to make Rust-style builders specifically, since in my experience read/write fields tend to be handled with just exposing a public field. Hence, this crate is meant to enable the method chaining `builder.foo(3).bar(4)` style of code where there is no `set_` prefix usually.

`derive_setters`, despite the poor choice of name, does generate the correct convention for builders. Examples:

* [`std::fs::DirBuilder::recursive`](https://doc.rust-lang.org/std/fs/struct.DirBuilder.html#method.recursive)
* [`std::thread::Builder::stack_size`](https://doc.rust-lang.org/std/thread/struct.Builder.html#method.stack_size)
* [Rust style guide on builders](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html)

You can use `#[setters(prefix = "set_")]` already to get the behavior you want.

**Comment by cottinisimone** [comment]
Ok. Thank you for the fast answer, makes sense
